"""Initial tables for carpenter, customer, furniture, orders

Revision ID: d7e1810ddbd8
Revises: 
Create Date: 2025-06-01 20:44:45.674930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e1810ddbd8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carpenters',
    sa.Column('carpenter_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('carpenter_id')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('furniture',
    sa.Column('furniture_id', sa.Integer(), nullable=False),
    sa.Column('carpenter_id', sa.Integer(), nullable=True),
    sa.Column('furniture_name', sa.String(length=50), nullable=False),
    sa.Column('furniture_cost', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('is_sold', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['carpenter_id'], ['carpenters.carpenter_id'], ),
    sa.PrimaryKeyConstraint('furniture_id')
    )
    op.create_table('carpenter_customer',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('carpenter_id', sa.Integer(), nullable=True),
    sa.Column('furniture_id', sa.Integer(), nullable=True),
    sa.Column('time_ordered', sa.DateTime(), nullable=True),
    sa.Column('returned', sa.Boolean(), nullable=True),
    sa.Column('remake_done', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['carpenter_id'], ['carpenters.carpenter_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['furniture_id'], ['furniture.furniture_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carpenter_customer')
    op.drop_table('furniture')
    op.drop_table('customers')
    op.drop_table('carpenters')
    # ### end Alembic commands ###
